# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfeJYCUnObgpYNk4q_IWrqlP_GdSGTj4
"""

import pandas as pd
from collections import Counter

# Load your dataset
data = pd.read_csv('updated_song_details.csv')

# Drop rows with missing values
data = data.dropna()

def predict_song_type(author_name):
    # Filter data for the specified author
    author_data = data[data['author'] == author_name]

    if author_data.empty:
        return "Author not found in the dataset."

    # Calculate average polarity, subjectivity, positive, negative, compound
    avg_polarity = author_data['polarity'].mean()
    avg_subjectivity = author_data['subjectivity'].mean()
    avg_positive = author_data['positive'].mean()
    avg_negative = author_data['negative'].mean()

    # Determine song type based on emotional and sentiment attributes
    if avg_polarity > 0.1 and avg_subjectivity > 0.5:
        song_type = "Joyful and emotional"
    elif avg_polarity < -0.1 and avg_subjectivity > 0.5:
        song_type = "Sad and emotional"
    elif avg_polarity > 0.1 and avg_subjectivity <= 0.5:
        song_type = "Uplifting and factual"
    elif avg_polarity < -0.1 and avg_subjectivity <= 0.5:
        song_type = "Melancholic and factual"
    else:
        song_type = "Neutral or mixed emotions"

    if avg_positive > 0.5:
        sentiment_type = "Generally Positive"
    elif avg_negative > 0.5:
        sentiment_type = "Generally Negative"
    else:
        sentiment_type = "Mixed Sentiments"

    # Get unique genres associated with the author
    genres = author_data['genre'].unique()

    # Extract and count instruments
    all_instruments = [instrument.strip().lower() for instruments in author_data['instruments'].str.split(',') for instrument in instruments if isinstance(instrument, str)]
    instrument_counts = Counter(all_instruments)

    # Select top 3 most used instruments
    most_used_instruments = [instrument for instrument, count in instrument_counts.most_common(3)]

    # Format the result as a text description
    result = f"Author: {author_name}\n"
    result += f"Song Type (Emotional): {song_type}\n"
    result += f"Sentiment Type: {sentiment_type}\n"
    result += f"Genres: {', '.join(genres)}\n"
    result += f"Most Used Instruments: {', '.join(most_used_instruments)}"

    return result

# Example usage:
author_name = "Freddie Mercury"  # Specify the author name
prediction_result = predict_song_type(author_name)
print(prediction_result)





