# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfeJYCUnObgpYNk4q_IWrqlP_GdSGTj4
"""

import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.sentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
from collections import Counter

# Download NLTK resources (only required if not already downloaded)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('vader_lexicon')

def analyze_emotional_stage(song_lyrics):
    if isinstance(song_lyrics, str):
        # Tokenize the lyrics into words
        words = word_tokenize(song_lyrics.lower())

        # Remove stopwords and non-alphabetic words
        stop_words = set(stopwords.words('english'))
        filtered_words = [word for word in words if word.isalpha() and word not in stop_words]

        # Perform sentiment analysis using VADER
        analyzer = SentimentIntensityAnalyzer()
        vader_scores = analyzer.polarity_scores(song_lyrics)

        # Perform sentiment analysis using TextBlob for polarity and subjectivity
        blob = TextBlob(song_lyrics)
        blob_polarity = blob.sentiment.polarity
        blob_subjectivity = blob.sentiment.subjectivity

        # Count word frequencies
        word_counts = Counter(filtered_words)

        # Extract top 4 keywords based on word frequencies
        top_keywords = [word for word, _ in word_counts.most_common(4)]

        return vader_scores['neg'], vader_scores['pos'], vader_scores['neu'], vader_scores['compound'], blob_polarity, blob_subjectivity, ', '.join(top_keywords)

    else:
        return None, None, None, None, None, None, None

# Load the CSV file into a DataFrame
df = pd.read_csv('song_details.csv')

# Apply the analyze_emotional_stage function to each row and update the DataFrame
df[['negative', 'positive', 'neutral', 'compound', 'polarity', 'subjectivity', 'keywords']] = df['lyrics'].apply(
    lambda lyrics: pd.Series(analyze_emotional_stage(lyrics))
)

# Format sentiment columns (2 decimal places)
df[['negative', 'positive', 'neutral', 'compound']] = df[['negative', 'positive', 'neutral', 'compound']].applymap(lambda x: f"{x:.2f}" if not pd.isnull(x) else None)
df['polarity'] = df['polarity'].apply(lambda x: f"{x:.2f}" if not pd.isnull(x) else None)
df['subjectivity'] = df['subjectivity'].apply(lambda x: f"{x:.2f}" if not pd.isnull(x) else None)

# Save the updated DataFrame back to a CSV file
df.to_csv('updated_song_details.csv', index=False)

print("All rows updated with sentiment scores (VADER and TextBlob) and keywords.")





